# ============================================================================
# KNAPSACK PRO FIX - Using SEPARATE Tokens (correct setup!)
# ============================================================================
# This pipeline demonstrates the FIX: each test suite uses its OWN
# Knapsack Pro token, ensuring tests are never mixed between suites.
# ============================================================================

steps:
  - label: ":ruby: Setup & Install"
    command: |
      echo "Ruby version:"
      ruby --version || echo "Ruby not installed on host"
    agents:
      queue: mac

  - wait

  # ============================================================================
  # FIX: Each suite uses its OWN token!
  # Knapsack Pro cache key = (branch, commit, node_total, api_token)
  # Different tokens = different queues = no mixing!
  # ============================================================================
  - group: ":white_check_mark: Unit Tests (SEPARATE token)"
    steps:
      - label: ":test_tube: Unit Tests {{.ID}}"
        parallelism: 10
        secrets:
          - KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT
        env:
          KNAPSACK_PRO_TEST_FILE_PATTERN: "spec/unit/**/*_spec.rb"
          KNAPSACK_PRO_LOG_LEVEL: "info"
        plugins:
          - docker#v5.11.0:
              image: "ruby:3.1"
              propagate-environment: true
              environment:
                - KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT
                - KNAPSACK_PRO_TEST_FILE_PATTERN
                - KNAPSACK_PRO_LOG_LEVEL
                - BUILDKITE_PARALLEL_JOB_COUNT
                - BUILDKITE_PARALLEL_JOB
                - BUILDKITE_BUILD_ID
                - BUILDKITE_COMMIT
                - BUILDKITE_BRANCH
        command: |
          echo "=== Unit Tests - Node $${BUILDKITE_PARALLEL_JOB} of $${BUILDKITE_PARALLEL_JOB_COUNT} ==="
          echo "Using SEPARATE token: KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT"
          
          export KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC=$${KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT}
          
          bundle install --jobs=4 --quiet
          
          echo "--- Running Knapsack Pro Queue Mode for Unit Tests"
          bundle exec rake knapsack_pro:queue:rspec["--format progress"]
        agents:
          queue: mac

  - group: ":white_check_mark: Acceptance Tests (SEPARATE token)"
    steps:
      - label: ":sparkles: Acceptance Tests {{.ID}}"
        parallelism: 10
        secrets:
          - KNAPSACK_PRO_TEST_SUITE_TOKEN_ACCEPTANCE
        env:
          KNAPSACK_PRO_TEST_FILE_PATTERN: "spec/acceptance/**/*_spec.rb"
          KNAPSACK_PRO_LOG_LEVEL: "info"
        plugins:
          - docker#v5.11.0:
              image: "ruby:3.1"
              propagate-environment: true
              environment:
                - KNAPSACK_PRO_TEST_SUITE_TOKEN_ACCEPTANCE
                - KNAPSACK_PRO_TEST_FILE_PATTERN
                - KNAPSACK_PRO_LOG_LEVEL
                - BUILDKITE_PARALLEL_JOB_COUNT
                - BUILDKITE_PARALLEL_JOB
                - BUILDKITE_BUILD_ID
                - BUILDKITE_COMMIT
                - BUILDKITE_BRANCH
        command: |
          echo "=== Acceptance Tests - Node $${BUILDKITE_PARALLEL_JOB} of $${BUILDKITE_PARALLEL_JOB_COUNT} ==="
          echo "Using SEPARATE token: KNAPSACK_PRO_TEST_SUITE_TOKEN_ACCEPTANCE"
          
          export KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC=$${KNAPSACK_PRO_TEST_SUITE_TOKEN_ACCEPTANCE}
          
          bundle install --jobs=4 --quiet
          
          echo "--- Running Knapsack Pro Queue Mode for Acceptance Tests"
          bundle exec rake knapsack_pro:queue:rspec["--format progress"]
        agents:
          queue: mac

  - wait

  - label: ":memo: Summary"
    command: |
      echo "=============================================="
      echo "FIX VERIFIED"
      echo "=============================================="
      echo ""
      echo "Each test suite used its OWN Knapsack Pro token:"
      echo "  - Unit Tests:       KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT"
      echo "  - Acceptance Tests: KNAPSACK_PRO_TEST_SUITE_TOKEN_ACCEPTANCE"
      echo ""
      echo "With separate tokens, each suite has its own queue"
      echo "and tests are NOT mixed between suites!"
      echo "=============================================="
    agents:
      queue: mac
