# ============================================================================
# KNAPSACK PRO BUG - Using SAME Token (will cause test mixing!)
# ============================================================================
# This pipeline demonstrates the BUG: both test suites use the SAME
# Knapsack Pro token, causing tests to be mixed between suites.
# ============================================================================

steps:
  - label: ":ruby: Setup & Install"
    command: |
      echo "Ruby version:"
      ruby --version || echo "Ruby not installed on host"
    agents:
      queue: mac

  - wait

  # ============================================================================
  # BUG: Both suites use the SAME token!
  # Knapsack Pro cache key = (branch, commit, node_total, api_token)
  # Same token = same queue = tests get MIXED!
  # ============================================================================
  - group: ":bug: Unit Tests (SAME token - will mix!)"
    steps:
      - label: ":test_tube: Unit Tests {{.ID}}"
        parallelism: 1
        secrets:
          - KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT
        env:
          KNAPSACK_PRO_TEST_FILE_PATTERN: "spec/unit/**/*_spec.rb"
          KNAPSACK_PRO_LOG_LEVEL: "info"
        plugins:
          - docker#v5.11.0:
              image: "ruby:3.1"
              propagate-environment: true
              environment:
                - KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT
                - KNAPSACK_PRO_TEST_FILE_PATTERN
                - KNAPSACK_PRO_LOG_LEVEL
                - BUILDKITE_PARALLEL_JOB_COUNT
                - BUILDKITE_PARALLEL_JOB
                - BUILDKITE_BUILD_ID
                - BUILDKITE_COMMIT
                - BUILDKITE_BRANCH
        command: |
          echo "=== Unit Tests - Node $${BUILDKITE_PARALLEL_JOB} of $${BUILDKITE_PARALLEL_JOB_COUNT} ==="
          echo "BUG: Using SAME token as Acceptance Tests!"
          
          export KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC=$${KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT}
          
          bundle install --jobs=4 --quiet
          
          echo "--- Running Knapsack Pro Queue Mode for Unit Tests"
          bundle exec rake knapsack_pro:queue:rspec["--format progress"]
        agents:
          queue: mac

  - group: ":bug: Acceptance Tests (SAME token - will mix!)"
    steps:
      - label: ":sparkles: Acceptance Tests {{.ID}}"
        parallelism: 1
        secrets:
          - KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT
        env:
          KNAPSACK_PRO_TEST_FILE_PATTERN: "spec/acceptance/**/*_spec.rb"
          KNAPSACK_PRO_LOG_LEVEL: "info"
        plugins:
          - docker#v5.11.0:
              image: "ruby:3.1"
              propagate-environment: true
              environment:
                - KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT
                - KNAPSACK_PRO_TEST_FILE_PATTERN
                - KNAPSACK_PRO_LOG_LEVEL
                - BUILDKITE_PARALLEL_JOB_COUNT
                - BUILDKITE_PARALLEL_JOB
                - BUILDKITE_BUILD_ID
                - BUILDKITE_COMMIT
                - BUILDKITE_BRANCH
        command: |
          echo "=== Acceptance Tests - Node $${BUILDKITE_PARALLEL_JOB} of $${BUILDKITE_PARALLEL_JOB_COUNT} ==="
          echo "BUG: Using SAME token as Unit Tests!"
          
          export KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC=$${KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT}
          
          bundle install --jobs=4 --quiet
          
          echo "--- Running Knapsack Pro Queue Mode for Acceptance Tests"
          bundle exec rake knapsack_pro:queue:rspec["--format progress"]
        agents:
          queue: mac

  - wait

  - label: ":memo: Summary"
    command: |
      echo "=============================================="
      echo "BUG REPRODUCTION"
      echo "=============================================="
      echo ""
      echo "Both test suites used the SAME Knapsack Pro token:"
      echo "  - Unit Tests:       KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT"
      echo "  - Acceptance Tests: KNAPSACK_PRO_TEST_SUITE_TOKEN_UNIT (SAME!)"
      echo ""
      echo "With the same token, both suites share the same queue"
      echo "and tests get MIXED between suites!"
      echo "=============================================="
    agents:
      queue: mac
