steps:
  - label: ":stopwatch: Test 1 - Sequential uploads"
    key: sequential
    command: .buildkite/scripts/test-sequential.sh

  - label: ":stopwatch: Test 2 - Concat then single upload"
    key: concat
    command: .buildkite/scripts/test-concat.sh

  - label: ":stopwatch: Test 3 - Parallel uploads"
    key: parallel
    command: .buildkite/scripts/test-parallel.sh
